### ISSUE TITLE
LGL22で動かない

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawaAppKies/kanazawApp_teamKIES#1]
LGL22で動作テストをしたが、エラーで動かない。

**Comment by kYukiA** [comment]
```
02-15 10:51:58.710: E/AndroidRuntime(2948): FATAL EXCEPTION: main
02-15 10:51:58.710: E/AndroidRuntime(2948): Process: jp.kanazawaapp.kit, PID: 2948
02-15 10:51:58.710: E/AndroidRuntime(2948): java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.kanazawaapp.kit/jp.kanazawaapp.kit.ARPreviewActivity}: android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread.access$800(ActivityThread.java:139)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.os.Handler.dispatchMessage(Handler.java:102)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.os.Looper.loop(Looper.java:136)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread.main(ActivityThread.java:5105)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at java.lang.reflect.Method.invokeNative(Native Method)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at java.lang.reflect.Method.invoke(Method.java:515)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at dalvik.system.NativeStart.main(Native Method)
02-15 10:51:58.710: E/AndroidRuntime(2948): Caused by: android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.view.LayoutInflater.inflate(LayoutInflater.java:458)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at jp.kanazawaapp.kit.ARPreviewActivity.onCreate(ARPreviewActivity.java:100)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.Activity.performCreate(Activity.java:5290)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
02-15 10:51:58.710: E/AndroidRuntime(2948):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
02-15 10:51:58.710: E/AndroidRuntime(2948):     ... 11 more

```
